language: node_js
node_js:
  - 14
services:
  - postgresql
addons:
  postgresql: '9.6'
dist: xenial
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - npm ci
before_script:
  - psql -c 'create database "past-stonks-test";' -U postgres

script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy:
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: past-stonks # see README
  api_key:
    secure: JDPDJIoL36PViBw7SU4DpLtuwr0Ktb3zr5mMZxMZdlyiMAC8++J0RTAOxehzdxBdNIEbYYypBnTV1TEQCGgqST4FAnhlONDk/zciSh6XSST/aEzlKt3vQvJddGqBFb68BN67sXCYa3Lba3IN/AGBS1w9yABjrdP0dmybu5Z8ItclMmA1ZJaRXIcBWtSV0N34E9kRHKFcEUhNttwxXHxJAEV+4kdAM93HaCpn54M8VKzbACXhPfBTt1sJnN2KrXTqI8zI/zcKep1CBkWnfW19Xy341MBfv47wnqmmjp6/dW50vNDokfyh0C+jcDE8s6N4gNomicspuIDD8aNfhla+76hzWH8+ZUz54YCQTHrUprIS5LaqqqCXJbYPY19v2vUlCca3VL/fM3n0k/0o6UegGsSu0tHdUQBY/TXwpaMUlB6YQMSeTlvaiLt9p3rJCklEmM2zGas2NgrQWZBcw5rh8gCl0mGcExWtZVTiX+QpHbMLHA+4rlKsklcZiZ42Av/QJMGbz3VLpw1nu4onTSpkVXJrl2D80T7r1v3VUsxRJE4bw877SHDZ6Gu8B4lciwBfdZIuOY5imactz6c5XtJdftK74EDUmRicc4IrglV8D332cqC8v/I/7cOu0sSKpF2Apa07IRqjQxIF1D8NxF0cjr/s8oFSej54tHidVxt9D2k=
