language: node_js
node_js:
  - 14
services:
  - postgresql
addons:
  postgresql: '9.6'
dist: xenial
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - npm ci
before_script:
  - psql -c 'create database "past-stonks-test";' -U postgres

script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy:
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: past-stonks # see README
  api_key:
    secure: a64Y0UNv1iZifBQYptRcdFuXE5FH6VdKNwm5IlMMmyufSq4AzJzlw5Bok3XRn8PnQtahoI1zByItDbvnmoeEDXfFvB+Y65DtQWrXgGp7rC+4bz0C6EFmLl1G3UMGrAS89c0poTqEfioaHA2BwVT9Nx2BBj47NX5QjxBlNBzJRwlxsxfStx3jLHJa5Gx1GtjglZzUWEslet699PbJwGdxy6qzb0ayP7FMW/zqdI2O3MGG4XzSwcJaqUUxOX4MI2fM2f4IrzMaeFskkBipNaW9Js/MSrViHoaKmhxRUo9l9FWqFZHPw/ye1BNrKC/uEfnMmTkO48we2SbQIGuQsYLh37k/vE5tIQJI/64y02lQKFIOMJM++XnbYvYdVA4vAbQQJiD5BNr4Cxnnn6lz/UfyM5zIF//5FRW2IBHd+uMAhiregQznAHVpssUdhGzThsC2h0hGtOTUi49sJTNI+B7nOrLNDWmaELNjew6Rk3/H5NxyfWHqWl9L1r0H/AtPYb4uacd71OagaC8OVDOpVg3goHPfoZBoY6A2VkwzdjJhJfNr48fBKB57BPNr0rARTp/wGgYi6RI7COGXXMaT4Ss4UQkVPL3c3XJO0WeAr/qGe0KHXsRNY7gj00l7IA4qppPTmKXyBkU9KEQPepeyb7x4zT62iJ846cHrZ80FqgGBCrU=
